---
generic-service:
  nameOverride: hmpps-activities-management-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-activities-management-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local    # override per environment
    tlsSecretName: activities-api-cert
    path: /
    annotations:
      # Secure the endpoints related to k8s jobs from outside the Kubernetes ingress
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /job/ {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Used to access resources like SQS queues and SNS topics
  serviceAccountName: hmpps-activities-management-api

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx256m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_MODE: "verify-full"
    HMPPS_SQS_USE_WEB_TOKEN: true
    SCHEDULE_AHEAD_DAYS: 60
    SCHEDULE_AHEAD_DAYS_ONLINE: 60
    MAX_APPOINTMENT_INSTANCES: 20000
    MAX_SYNC_APPOINTMENT_INSTANCE_ACTIONS: 500
    FEATURE_EVENTS_SNS_ENABLED: false
    FEATURE_EVENT_ACTIVITIES_ACTIVITY_SCHEDULE_CREATED: true
    FEATURE_EVENT_ACTIVITIES_ACTIVITY_SCHEDULE_AMENDED: true
    FEATURE_EVENT_ACTIVITIES_SCHEDULED_INSTANCE_AMENDED: true
    FEATURE_EVENT_ACTIVITIES_PRISONER_ALLOCATED: true
    FEATURE_EVENT_ACTIVITIES_PRISONER_ALLOCATION_AMENDED: true
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_CREATED: true
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_AMENDED: true
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_EXPIRED: true
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_CREATED: true
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_UPDATED: true
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_CANCELLED: true
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_DELETED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_ACTIVITIES_CHANGED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_APPOINTMENTS_CHANGED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_RECEIVED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_RELEASED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_MERGED: true
    FEATURE_EVENT_PRISON_OFFENDER_SEARCH_PRISONER_ALERTS_UPDATED: true
    FEATURE_EVENT_INCENTIVES_IEP_REVIEW_INSERTED: true
    FEATURE_EVENT_INCENTIVES_IEP_REVIEW_UPDATED: true
    FEATURE_EVENT_INCENTIVES_IEP_REVIEW_DELETED: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_CELL_MOVE: true
    FEATURE_EVENT_PRISON_OFFENDER_EVENTS_PRISONER_NON_ASSOCIATION_DETAIL_CHANGED: true
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: false
    FEATURE_AUDIT_SERVICE_LOCAL_ENABLED: true
    FEATURE_MIGRATE_SPLIT_REGIME_ENABLED: false
    FEATURE_OFFENDER_MERGE_ENABLED: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-activities-management-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    activities-domain-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_ACTIVITIES_QUEUE_NAME: "sqs_queue_name"
    activities-domain-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_ACTIVITIES_DLQ_NAME: "sqs_queue_name"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"
    digital-prison-reporting:
      DPR_USER: "DPR_USER"
      DPR_PASSWORD: "DPR_PASSWORD"
    sentry:
      SENTRY_DSN: "SENTRY_DSN"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-activities-management-api

cron:
  allocationsDeallocate: "0 22 * * *"
  allocationsActivate: "0 2 * * *"
  appointmentAttendees: "30 2 * * *"
  createScheduledInstances: "0 3 * * *"
  attendanceRecords: "0 4 * * *"
