version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: activities-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: activities-management-db
      POSTGRES_USER: activities-management
      POSTGRES_PASSWORD: activities-management
      DPR_USER: dpr_user
      DPR_PASSWORD: dpr_password

  local-stack-aws:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: local-sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  prison-api:
    image: wiremock/wiremock:latest
    container_name: prison-api
    ports:
      - "8091:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

  prisoner-search-api:
    image: wiremock/wiremock:latest
    container_name: prisoner-search-api
    ports:
      - "8092:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

  oauth-server:
    image: wiremock/wiremock:latest
    container_name: oauth-server
    ports:
      - "8090:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

networks:
  hmpps:
