insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'GTI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'GTI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'GTI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'GTI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'GTI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'GTI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'GTI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'GTI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'GTI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'GTI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'FNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'FNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'FNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'FNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'FNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'FNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'FNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'FNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'FNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'FNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LTI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LTI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LTI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LTI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LTI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LTI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LTI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LTI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LTI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LTI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WII'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WII'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WII'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WII'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WII'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WII'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WII'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WII'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WII'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WII');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HII'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HII'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HII'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HII'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HII'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HII'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HII'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HII'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HII'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HII');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'GHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'GHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'GHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'GHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'GHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'GHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'GHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'GHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'GHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'GHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'MRI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'MRI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'MRI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'MRI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'MRI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'MRI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'MRI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'MRI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'MRI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'MRI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BAI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BAI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BAI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BAI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BAI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BAI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BAI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BAI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BAI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BAI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WRI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WRI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WRI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WRI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WRI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WRI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WRI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WRI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WRI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WRI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BFI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BFI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BFI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BFI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BFI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BFI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BFI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BFI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BFI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BFI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BSI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BSI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BSI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BSI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BSI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BSI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BSI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BSI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BSI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BSI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'FSI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'FSI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'FSI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'FSI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'FSI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'FSI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'FSI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'FSI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'FSI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'FSI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SFI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SFI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SFI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SFI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SFI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SFI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SFI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SFI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SFI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SFI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HMI');;
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WEI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WEI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WEI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WEI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WEI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WEI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WEI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WEI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WEI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WEI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LII'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LII'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LII'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LII'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LII'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LII'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LII'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LII'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LII'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LII');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'MHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'MHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'MHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'MHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'MHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'MHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'MHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'MHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'MHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'MHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'ONI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'ONI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'ONI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'ONI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'ONI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'ONI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'ONI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'ONI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'ONI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'ONI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WTI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WTI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WTI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WTI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WTI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WTI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WTI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WTI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WTI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WTI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'CDI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'CDI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'CDI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'CDI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'CDI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'CDI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'CDI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'CDI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'CDI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'CDI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HPI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HPI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HPI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HPI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HPI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HPI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HPI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HPI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HPI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HPI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'MTI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'MTI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'MTI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'MTI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'MTI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'MTI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'MTI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'MTI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'MTI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'MTI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'EEI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'EEI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'EEI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'EEI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'EEI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'EEI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'EEI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'EEI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'EEI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'EEI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'PDI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'PDI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'PDI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'PDI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'PDI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'PDI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'PDI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'PDI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'PDI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'PDI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'VEI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'VEI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'VEI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'VEI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'VEI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'VEI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'VEI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'VEI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'VEI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'VEI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'NWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'NWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'NWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'NWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'NWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'NWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'NWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'NWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'NWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'NWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'CLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'CLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'CLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'CLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'CLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'CLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'CLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'CLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'CLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'CLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'MSI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'MSI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'MSI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'MSI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'MSI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'MSI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'MSI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'MSI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'MSI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'MSI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'RCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'RCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'RCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'RCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'RCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'RCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'RCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'RCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'RCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'RCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'GNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'GNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'GNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'GNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'GNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'GNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'GNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'GNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'GNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'GNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'AYI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'AYI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'AYI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'AYI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'AYI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'AYI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'AYI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'AYI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'AYI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'AYI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BRI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BRI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BRI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BRI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BRI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BRI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BRI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BRI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BRI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BRI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WLI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WLI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WLI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WLI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WLI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WLI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WLI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WLI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WLI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WLI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'PNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'PNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'PNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'PNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'PNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'PNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'PNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'PNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'PNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'PNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'EXI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'EXI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'EXI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'EXI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'EXI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'EXI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'EXI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'EXI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'EXI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'EXI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'CWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'CWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'CWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'CWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'CWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'CWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'CWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'CWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'CWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'CWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'DAI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'DAI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'DAI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'DAI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'DAI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'DAI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'DAI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'DAI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'DAI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'DAI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'GMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'GMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'GMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'GMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'GMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'GMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'GMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'GMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'GMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'GMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'EYI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'EYI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'EYI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'EYI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'EYI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'EYI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'EYI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'EYI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'EYI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'EYI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'PVI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'PVI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'PVI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'PVI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'PVI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'PVI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'PVI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'PVI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'PVI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'PVI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WSI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WSI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WSI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WSI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WSI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WSI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WSI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WSI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WSI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WSI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BXI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BXI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BXI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BXI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BXI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BXI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BXI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BXI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BXI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BXI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HOI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HOI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HOI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HOI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HOI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HOI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HOI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HOI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HOI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HOI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'ISI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'ISI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'ISI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'ISI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'ISI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'ISI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'ISI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'ISI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'ISI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'ISI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'DMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'DMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'DMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'DMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'DMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'DMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'DMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'DMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'DMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'DMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'DTI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'DTI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'DTI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'DTI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'DTI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'DTI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'DTI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'DTI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'DTI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'DTI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'NMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'NMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'NMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'NMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'NMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'NMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'NMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'NMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'NMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'NMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'CFI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'CFI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'CFI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'CFI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'CFI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'CFI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'CFI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'CFI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'CFI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'CFI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'UKI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'UKI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'UKI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'UKI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'UKI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'UKI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'UKI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'UKI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'UKI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'UKI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'RNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'RNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'RNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'RNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'RNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'RNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'RNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'RNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'RNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'RNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SKI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SKI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SKI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SKI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SKI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SKI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SKI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SKI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SKI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SKI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'BWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'BWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'BWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'BWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'BWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'BWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'BWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'BWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'BWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'BWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LFI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LFI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LFI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LFI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LFI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LFI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LFI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LFI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LFI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LFI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'FDI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'FDI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'FDI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'FDI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'FDI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'FDI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'FDI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'FDI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'FDI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'FDI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HDI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HDI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HDI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HDI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HDI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HDI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HDI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HDI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HDI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HDI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HVI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HVI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HVI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HVI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HVI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HVI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HVI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HVI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HVI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HVI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'HBI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'HBI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'HBI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'HBI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'HBI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'HBI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'HBI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'HBI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'HBI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'HBI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'KMI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'KMI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'KMI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'KMI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'KMI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'KMI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'KMI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'KMI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'KMI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'KMI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'KVI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'KVI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'KVI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'KVI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'KVI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'KVI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'KVI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'KVI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'KVI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'KVI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LYI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LYI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LYI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LYI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LYI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LYI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LYI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LYI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LYI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LYI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'NSI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'NSI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'NSI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'NSI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'NSI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'NSI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'NSI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'NSI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'NSI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'NSI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'UPI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'UPI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'UPI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'UPI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'UPI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'UPI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'UPI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'UPI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'UPI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'UPI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SPI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SPI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SPI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SPI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SPI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SPI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SPI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SPI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SPI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SPI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'EHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'EHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'EHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'EHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'EHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'EHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'EHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'EHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'EHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'EHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SUI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SUI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SUI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SUI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SUI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SUI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SUI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SUI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SUI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SUI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'TCI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'TCI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'TCI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'TCI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'TCI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'TCI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'TCI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'TCI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'TCI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'TCI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'AGI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'AGI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'AGI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'AGI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'AGI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'AGI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'AGI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'AGI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'AGI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'AGI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'DWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'DWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'DWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'DWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'DWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'DWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'DWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'DWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'DWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'DWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'DHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'DHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'DHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'DHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'DHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'DHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'DHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'DHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'DHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'DHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'ESI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'ESI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'ESI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'ESI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'ESI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'ESI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'ESI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'ESI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'ESI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'ESI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'EWI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'EWI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'EWI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'EWI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'EWI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'EWI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'EWI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'EWI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'EWI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'EWI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'FHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'FHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'FHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'FHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'FHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'FHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'FHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'FHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'FHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'FHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'LNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'LNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'LNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'LNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'LNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'LNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'LNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'LNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'LNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'LNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'NHI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'NHI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'NHI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'NHI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'NHI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'NHI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'NHI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'NHI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'NHI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'NHI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'SDI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'SDI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'SDI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'SDI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'SDI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'SDI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'SDI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'SDI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'SDI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'SDI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'STI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'STI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'STI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'STI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'STI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'STI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'STI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'STI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'STI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'STI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'CKI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'CKI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'CKI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'CKI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'CKI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'CKI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'CKI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'CKI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'CKI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'CKI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'FYI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'FYI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'FYI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'FYI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'FYI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'FYI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'FYI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'FYI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'FYI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'FYI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WNI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WNI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WNI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WNI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WNI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WNI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WNI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WNI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WNI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WNI');
insert into prison_pay_band (display_sequence, nomis_pay_band, pay_band_alias, pay_band_description, prison_code)
values (1,  1,  'Pay band 1 (Lowest)', 'Pay band 1 (Lowest)', 'WYI'),
       (2,  2,  'Pay band 2', 'Pay band 2', 'WYI'),
       (3,  3,  'Pay band 3', 'Pay band 3', 'WYI'),
       (4,  4,  'Pay band 4', 'Pay band 4', 'WYI'),
       (5,  5,  'Pay band 5', 'Pay band 5', 'WYI'),
       (6,  6,  'Pay band 6', 'Pay band 6', 'WYI'),
       (7,  7,  'Pay band 7', 'Pay band 7', 'WYI'),
       (8,  8,  'Pay band 8', 'Pay band 8', 'WYI'),
       (9,  9,  'Pay band 9', 'Pay band 9', 'WYI'),
       (10, 10, 'Pay band 10 (Highest)', 'Pay band 10 (Highest)', 'WYI');