#
# The "-dev" for use in the dev environment (profile enabled in the helm dev config).
#
spring:
  flyway:
    locations: classpath:/migration,classpath:/reference_data/common,classpath:/reference_data/dev
