#
# The "-dev" for use in the dev environment (profile enabled in the helm dev config).
#
spring:
  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

aws:
  s3:
    ap:
      bucket: moj-reg-dev