#
# The "-local" profile is for running the API service locally against pre-existing
# docker containers that are listening on a known port numbers for a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:
spring:
  flyway:
    locations: classpath:/migration/common,classpath:/migration/data

  datasource:
    url: 'jdbc:postgresql://localhost/activities-management-db?sslmode=prefer'
    username: 'activities-management'
    password: 'activities-management'

  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

system:
  client:
    id: activities-management-admin-1
    secret: secret

# Container-provider local auth server
hmpps:
  auth:
    # url: http://localhost:8090/auth
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

prison:
  api:
    url: https://api-dev.prison.service.justice.gov.uk
    timeout: 10s

