#
# The "-local" profile is for running the API service locally against pre-existing
# docker containers that are listening on a known port numbers for a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:
spring:
  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}?sslmode=${DB_SSL_MODE}'
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

system:
  client:
    id: ${SYSTEM_CLIENT_ID}
    secret: ${SYSTEM_CLIENT_SECRET}

# Container-provider local auth server
hmpps:
  auth:
    # url: http://localhost:8090/auth
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

prison:
  api:
    url: https://prison-api-dev.prison.service.justice.gov.uk
    timeout: 10s

prisoner-search:
  api:
    url: https://prisoner-search-dev.prison.service.justice.gov.uk
    timeout: 10s

case-notes:
  api:
    url: https://dev.offender-case-notes.service.justice.gov.uk
    timeout: 10s

non-associations:
  api:
    url: https://non-associations-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

incentives:
  api:
    url: https://incentives-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

manage.adjudications:
  api:
    url: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

locations-inside-prison:
  api:
    url: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

nomis-mapping:
  api:
    url: https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk
    timeout: 10s

jobs:
  create-scheduled-instances:
    days-in-advance: ${SCHEDULE_AHEAD_DAYS:14}

online:
  create-scheduled-instances:
    days-in-advance: ${SCHEDULE_AHEAD_DAYS_ONLINE:14}

applications:
  max-appointment-instances: ${MAX_APPOINTMENT_INSTANCES:20000}
  max-sync-appointment-instance-actions: ${MAX_SYNC_APPOINTMENT_INSTANCE_ACTIONS:500}

migrate:
  ACTIVITIES_LIVE: RSI,LPI,WDI,IWI,FKI,FMI,WMI,GTI,LTI,BCI,LEI,FNI,WII,RCI,HII,FSI,DMI,MTI,RNI,SLI,MDI,EEI,EYI
  APPOINTMENTS_LIVE: RSI,LPI,WDI,IWI,FKI,FMI,WMI,GTI,LTI,BCI,LEI,FNI,WII,RCI,HII,FSI,DMI,MTI,RNI,SLI,MDI,EEI,EYI
  PRISONS_LIVE: RSI,LPI,WDI,IWI,FKI,FMI,WMI,GTI,LTI,BCI,LEI,FNI

prison-locations:
  PRISONS_WITH_REGEX_LOCATION_CONFIGS: RSI,BCI,CDI,EYI,FNI,HEI,MDI,NHI,WNI,IWI,LHI,RNI,WLI,WEI,WRI
  
aws:
  s3:
    ap:
      bucket: moj-reg-dev
      project: hmpps-activities-management-dev
