#
# The "-localstack" profile is for running the API service locally against pre-existing
# docker containers that are listening on a known port numbers for a localstack container (4566).
#
# Most values are inherited from - application.yml - except the following:
spring:
  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}?sslmode=${DB_SSL_MODE}'
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

system:
  client:
    id: activities-management-admin-1
    secret: secret

# Container-provider local auth server
hmpps:
  auth:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

prison:
  api:
    url: https://prison-api-dev.prison.service.justice.gov.uk
    timeout: 10s

prisoner-search:
  api:
    url: https://prisoner-search-dev.prison.service.justice.gov.uk
    timeout: 10s

case-notes:
  api:
    url: https://dev.offender-case-notes.service.justice.gov.uk
    timeout: 10s

non-associations:
  api:
    url: https://non-associations-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

incentives:
  api:
    url: https://incentives-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

manage.adjudications:
  api:
    url: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

locations-inside-prison:
  api:
    url: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
    timeout: 10s

nomis-mapping:
  api:
    url: https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk
    timeout: 10s

jobs:
  create-scheduled-instances:
    days-in-advance: ${SCHEDULE_AHEAD_DAYS:14}

online:
  create-scheduled-instances:
    days-in-advance: ${SCHEDULE_AHEAD_DAYS_ONLINE:14}

applications:
  max-appointment-instances: ${MAX_APPOINTMENT_INSTANCES:20000}
  max-sync-appointment-instance-actions: ${MAX_SYNC_APPOINTMENT_INSTANCE_ACTIONS:500}

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:14566
  queues:
    activities:
      queueName: activities-queue
      subscribeFilter: '{"eventType":[ "prisoner-offender-search.prisoner.received", "prisoner-offender-search.prisoner.released", "prison-offender-events.prisoner.activities-changed", "prison-offender-events.prisoner.appointments-changed", "prison-offender-search.prisoner.alerts-updated"]}'
      dlqName: activities-dead-letter-queue
      subscribeTopicId: domainevents
      dlqMaxReceiveCount: 1
      visibilityTimeout: 1
    domaineventsqueue:
      queueName: domainevents-queue
      subscribeTopicId: domainevents
    outboundtestqueue:
      dlqName: ${random.uuid}
      queueName: ${random.uuid}
      subscribeTopicId: outboundtopic
      subscribeFilter: '{"eventType":[ "test.type"] }'
    audit:
      queueName: ${random.uuid}
    updatefromexternalsystemevents:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    activitiesmanagementjobs:
      queueName:  ${random.uuid}
      dlqName:  ${random.uuid}
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic
    outboundtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
feature:
  event:
    prison-offender-events:
      prisoner:
        activities-changed: true
        appointments-changed: true
    prisoner-offender-search:
      prisoner:
        received: true
        released: true
        alerts-updated: true
    activities:
      prisoner:
        allocation-amended: true
      activity-schedule:
        amended: true
  jobs.sqs:
    schedules.enabled: true
    deallocate.ending.enabled: true
    deallocate.expiring.enabled: true
    activate.allocations.enabled: true
    manage.attendances.enabled: true

migrate:
  ACTIVITIES_LIVE: RSI,LEI
  APPOINTMENTS_LIVE: RSI,LEI
  PRISONS_LIVE: RSI

prison-locations:
  PRISONS_WITH_REGEX_LOCATION_CONFIGS: RSI,BCI,CDI,EYI,FNI,HEI,MDI,NHI,WNI,IWI,LHI,RNI,WLI,WEI,WRI

aws:
  s3:
    ap:
      bucket: default-localstack-bucket
      project: default-localstack-project
  sqs:
    endpoint: https://sqs.localhost.localstack.cloud:4567/
