#
# The "-dev" for use in the dev environment (profile enabled in the helm dev config).
#
spring:
  flyway:
    locations: classpath:/migration/common,classpath:/migration/data

jobs:
  create-activity-sessions:
    days-in-advance: ${CREATE_ACTIVITY_SESSIONS_DAYS_IN_ADVANCE:0}
