Activities API.http:

### Retrieve an activity
// @no-log
< {%
    request.variables.set("activityId", "1")
%}

GET {{ baseUrl }}/activities/{{activityId}}/filtered?includeScheduledInstances=false
Authorization: Bearer {{$auth.token("auth-token")}}
Content-Type: application/json

### Retrieve exclusions history for an allocation
// @no-log
< {%
    request.variables.set("allocationId", "8569")
%}

GET {{ baseUrl }}/allocations/id/{{ allocationId }}/exclusions/history
Authorization: Bearer {{$auth.token("auth-token")}}
Content-Type: application/json

### Returns allocations as part of event review
// @no-log
< {%
    request.variables.set("prisonCode", "MDI")
%}

GET {{ baseUrl }}/event-review/prison/{{prisonCode}}?date=2023-05-10
Authorization: Bearer {{$auth.token("auth-token")}}
Content-Type: application/json
