Activities API.http:

### Retrieve an activity

< {%
    request.variables.set("activityId", "1")
%}

GET {{ baseUrl }}/activities/{{activityId}}/filtered?includeScheduledInstances=false
Authorization: Bearer {{$auth.token("auth-token")}}


### Retrieve exclusions history for an allocation

< {%
    request.variables.set("allocationId", "20")
%}

GET {{ baseUrl }}/allocations/id/{{ allocationId }}/exclusions/history
Authorization: Bearer {{$auth.token("auth-token")}}

###