package uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.model

import io.swagger.v3.oas.annotations.media.Schema
import java.time.LocalDate
import java.time.LocalDateTime

@Schema(description = "Describes one instance of a planned deallocation")
data class PlannedDeallocation(

  @Schema(description = "The internally-generated ID for this planned de-allocation", example = "24")
  val id: Long,

  @Schema(description = "The planned de-allocation date ", example = "2023-07-31")
  val plannedDate: LocalDate,

  @Schema(description = "The person who planned the de-allocation", example = "ADMIN")
  val plannedBy: String,

  @Schema(description = "The planned reason generated by the system", example = "PLANNED")
  val plannedReason: DeallocationReason,

  @Schema(description = "The system time when the de-allocation plan was made", example = "2023-07-10 14:54")
  val plannedAt: LocalDateTime,

)
