package uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.model.audit

enum class AuditEventType {

  ACTIVITY_CREATED,
  ACTIVITY_UPDATED,
  PRISONER_ALLOCATED,
  PRISONER_DEALLOCATED,
  PRISONER_SUSPENDED_FROM_ACTIVITY,
  PRISONER_UNSUSPENDED_FROM_ACTIVITY,
  PRISONER_ADDED_TO_WAITING_LIST,
  PRISONER_REJECTED_FROM_WAITING_LIST,
  PRISONER_ACCEPTED_FROM_WAITING_LIST,
  BONUS_PAYMENT_MADE_FOR_ACTIVITY_ATTENDANCE,
  INCENTIVE_LEVEL_WARNING_GIVEN_FOR_ACTIVITY_ATTENDANCE,
}
