#Prisons enabled for external activities
AGI=Askham Grange
EHI=Standford Hill
ESI=East Sutton Park
FDI=Ford
GNI=Grendon
HDI=Hatfield
HVI=Haverigg
KMI=Kirkham
KVI=Kirklevington Grange
LNI=Low Newton
LYI=Leyhill
SPI=Spring Hill
SUI=Sudbury
TCI=Thorn Cross
UKI=Usk
UPI=Prescoed
WNI=Werrington
WYI=Wetherby
