apiVersion: batch/v1
kind: CronJob
metadata:
  name: activities-metrics
spec:
  schedule: "0 3 * * *" # 3am every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: activities-metrics-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST http://hmpps-activities-management-api/job/activities-metrics
