apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-scheduled-instances
spec:
  schedule: "0 3 * * *" # 3am every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
          - name: hmpps-activities-management-api
            image: ghcr.io/ministryofjustice/hmpps-devops-tools
            args:
              - /bin/sh
              - -c
              - curl --fail -X POST http://hmpps-activities-management-api/job/create-scheduled-instances
