apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-attendance-records
spec:
  schedule: "0 4 * * *" # 4am every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
          - name: hmpps-activities-management-api
            image: ghcr.io/ministryofjustice/hmpps-devops-tools
            args:
              - /bin/sh
              - -c
              - curl -X POST http://hmpps-activities-management-api/job/create-attendance-records
