apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-scheduled-instances
spec:
  schedule: "{{ .Values.cron.createScheduledInstances }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: create-scheduled-instances-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST http://hmpps-activities-management-api/job/create-scheduled-instances
