apiVersion: batch/v1
kind: CronJob
metadata:
  name: deallocate-offenders
spec:
  schedule: "0 22 * * *" # 10pm every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
          - name: deallocate-offenders-job
            image: ghcr.io/ministryofjustice/hmpps-devops-tools
            args:
              - /bin/sh
              - -c
              - curl --fail -X POST http://hmpps-activities-management-api/job/deallocate-offenders
