apiVersion: batch/v1
kind: CronJob
metadata:
  name: fix-zero-pay-deallocate
spec:
  schedule:  "{{ .Values.cron.fixZeroPayDeallocate }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: deallocate-fixzeropay-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST "http://hmpps-activities-management-api/job/fix-zero-pay?deallocate=true&prisonCode={{ .Values.cron.datafix.prisonCode }}&activityScheduleId={{ .Values.cron.datafix.activityScheduleId }}"
