apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-attendance-records
spec:
  schedule: "0 4 * * *" # 4am every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
          - name: manage-attendance-records-job
            image: ghcr.io/ministryofjustice/hmpps-devops-tools
            args:
              - /bin/sh
              - -c
              - curl --fail -X POST http://hmpps-activities-management-api/job/manage-attendance-records?withExpiry=true
