apiVersion: batch/v1
kind: CronJob
metadata:
  name: deallocate-allocations-expiring
spec:
  schedule:  "{{ .Values.cron.allocationsDeallocateExpiring }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: deallocate-allocations-expiring-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST http://hmpps-activities-management-api/job/manage-allocations?withDeallocateExpiring=true
