---
# Per environment values which override defaults in hmpps-activities-management-api/values.yaml

generic-service:
  ingress:
    host: activities-api.prison.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx1024m"
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-offender-search.prison.service.justice.gov.uk
    CASE_NOTES_API_URL: https://offender-case-notes.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: true
    FEATURE_EVENTS_SNS_ENABLED: true
    FEATURE_EVENT_ACTIVITIES_ACTIVITY_SCHEDULE_CREATED: false
    FEATURE_EVENT_ACTIVITIES_ACTIVITY_SCHEDULE_AMENDED: false
    FEATURE_EVENT_ACTIVITIES_SCHEDULED_INSTANCE_AMENDED: false
    FEATURE_EVENT_ACTIVITIES_PRISONER_ALLOCATED: false
    FEATURE_EVENT_ACTIVITIES_PRISONER_ALLOCATION_AMENDED: false
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_CREATED: false
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_AMENDED: false
    FEATURE_EVENT_ACTIVITIES_PRISONER_ATTENDANCE_EXPIRED: false
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_CREATED: false
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_UPDATED: false
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_CANCELLED: false
    FEATURE_EVENT_APPOINTMENTS_APPOINTMENT_INSTANCE_DELETED: false


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
