---
# Per environment values which override defaults in hmpps-activities-management-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: activities-api-dev.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api-dev.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
    CASE_NOTES_API_URL: https://dev.offender-case-notes.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: dev
    SCHEDULE_AHEAD_DAYS: 14
    SCHEDULE_AHEAD_DAYS_ONLINE: 14
    FEATURE_EVENTS_SNS_ENABLED: true
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: true

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"
    bsi-pen-test-1: "54.37.241.156/30"
    bsi-pen-test-2: "167.71.136.237/32"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
