---
# Per environment values which override defaults in hmpps-activities-management-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: activities-api-dev.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    CASE_NOTES_API_URL: https://dev.offender-case-notes.service.justice.gov.uk
    NON_ASSOCIATIONS_API_URL: https://non-associations-api-dev.hmpps.service.justice.gov.uk
    INCENTIVES_API_URL: https://incentives-api-dev.hmpps.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: dev
    SCHEDULE_AHEAD_DAYS: 14
    SCHEDULE_AHEAD_DAYS_ONLINE: 14
    FEATURE_EVENTS_SNS_ENABLED: true
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: true
    SENTRY_ENVIRONMENT: development
    HEARINGS_ADJUDICATION_SERVICE: true

  resources:
    requests:
      cpu: 10m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 2048Mi

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

# We are overriding the times in development due to core service dependencies being switched off overnight e.g. prisoner search API.
cron:
  allocationsDeallocateEnding: "30 6 * * *"
  allocationsDeallocateExpiring: "30 20 * * *"
  allocationsActivate: "45 6 * * *"
  appointmentAttendees: "45 6 * * *"
  createScheduledInstances: "0 7 * * *"
  attendanceRecords: "15 7 * * *"
