---
# Per environment values which override defaults in hmpps-activities-management-api/values.yaml

generic-service:
  ingress:
    host: activities-api.prison.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx1024m"
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search.prison.service.justice.gov.uk
    CASE_NOTES_API_URL: https://offender-case-notes.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: true
    FEATURE_EVENTS_SNS_ENABLED: true

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
