---
# Per environment values which override defaults in hmpps-activities-management-api/values.yaml

generic-service:
  ingress:
    host: activities-api.prison.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx1024m"
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search.prison.service.justice.gov.uk
    CASE_NOTES_API_URL: https://offender-case-notes.service.justice.gov.uk
    NON_ASSOCIATIONS_API_URL: https://non-associations-api.hmpps.service.justice.gov.uk
    INCENTIVES_API_URL: https://incentives-api.hmpps.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api.hmpps.service.justice.gov.uk
    LOCATIONS_INSIDE_PRISON_API_URL: https://locations-inside-prison-api.hmpps.service.justice.gov.uk
    NOMIS_MAPPING_API_URL: https://nomis-sync-prisoner-mapping.hmpps.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    FEATURE_AUDIT_SERVICE_HMPPS_ENABLED: true
    FEATURE_EVENTS_SNS_ENABLED: true
    SENTRY_ENVIRONMENT: production
    ACTIVITIES_LIVE: RSI,LPI,WDI,FMI,FKI,IWI,WMI,GTI,LTI,BCI,FNI,MTI,LEI,RCI,FSI,DMI,WII,HII,RNI,MDI,LFI,LHI,PVI,EYI,PDI,SLI,SNI,HOI,BXI,WEI,WSI,VEI,BLI,PNI,CFI,DWI,LCI,ISI,HEI,MHI,AYI,BRI,BSI,BAI,BNI,NMI,WLI
    APPOINTMENTS_LIVE: RSI,LPI,WDI,FMI,FKI,IWI,WMI,GTI,LTI,BCI,FNI,MTI,LEI,RCI,FSI,DMI,WII,HII,RNI,MDI,LFI,LHI,PVI,EYI,PDI,SLI,SNI,HOI,BXI,WEI,WSI,VEI,BLI,PNI,CFI,DWI,LCI,ISI,HEI,MHI,AYI,BRI,BSI,BAI,BNI,NMI,WLI
    PRISONS_LIVE: RSI,LPI,WDI,FMI,FKI,IWI,WMI,GTI,LTI,BCI,FNI,MTI,LEI,FSI,DMI,HII,WII,RCI,RNI,MDI,LFI,LHI,EYI,PDI,SLI,SNI,BXI,PVI,WEI,WSI,VEI,BLI,HOI,PNI,CFI,DWI,LCI,ISI,HEI,MHI,AYI,BRI,BSI,BAI,BNI,NMI,WLI
    AWS_S3_AP_BUCKET: moj-reg-prod
    AWS_S3_AP_PROJECT: hmpps-activities-management-prod
    PRISONS_WITH_REGEX_LOCATION_CONFIGS: RSI,BCI,CDI,EYI,FNI,HEI,MDI,NHI,WNI,IWI,LHI,RNI,WLI,WEI,WRI

  resources:
    requests:
      cpu: 10m
      memory: 768Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

cron:
  fixZeroPayDeallocate: "0 22 09 03 *"
  fixZeroPayReallocate: "0 5 10 03 *"

  datafix:
    prisonCode: "WSI"
    activityScheduleId: "7760"
