package uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.service

import uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.entity.EventType
import uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.model.PrisonerScheduledEvents
import uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.model.ScheduledEvent
import java.time.LocalDate
import java.time.LocalTime

/*
 This object is used in testing only.

 Used to create mocked response objects for the tests in
 * ScheduledEventControllerTest
 * ScheduledEventServiceTest

 These objects represent those that are returned for unlock lists and calendar view, and are produced
 by the ScheduledEventService and returned to clients via the ScheduledEventController.
 */

object PrisonerScheduledEventsFixture {
  fun instance(
    prisonCode: String = "MDI",
    prisonerNumbers: Set<String> = setOf("GF10001"),
    startDate: LocalDate = LocalDate.of(2022, 10, 1),
    endDate: LocalDate = LocalDate.of(2022, 11, 29),
    appointments: List<ScheduledEvent> = listOf(appointmentInstance()),
    activities: List<ScheduledEvent> = listOf(activityInstance()),
    visits: List<ScheduledEvent> = listOf(visitInstance()),
    courtHearings: List<ScheduledEvent> = listOf(courtHearingInstance()),
    adjudications: List<ScheduledEvent> = listOf(adjudicationInstance()),
    externalTransfers: List<ScheduledEvent> = listOf(externalTransferInstance()),
  ) = PrisonerScheduledEvents(
    prisonCode = prisonCode,
    prisonerNumbers = prisonerNumbers,
    startDate = startDate,
    endDate = endDate,
    appointments = appointments,
    activities = activities,
    visits = visits,
    courtHearings = courtHearings,
    externalTransfers = externalTransfers,
    adjudications = adjudications,
  )

  fun appointmentInstance(
    prisonCode: String = "MDI",
    eventSource: String = "SAA",
    eventType: String = EventType.APPOINTMENT.name,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    appointmentSeriesId: Long? = 10L,
    appointmentId: Long? = 11L,
    appointmentAttendeeId: Long? = 12L,
    internalLocationId: Long? = 102,
    internalLocationCode: String? = "MDI-INDUCTION",
    internalLocationUserDescription: String? = "User description",
    internalLocationDescription: String? = "Induction classroom",
    eventId: Long? = null,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    categoryCode: String? = "GOVE",
    categoryDescription: String? = "Governor",
    summary: String? = "Appointment",
    comments: String? = "Dont be late",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime = LocalTime.of(13, 0, 0),
    priority: Int = 5,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = null,
    bookingId = bookingId,
    prisonerNumber = prisonerNumber,
    internalLocationId = internalLocationId,
    internalLocationCode = internalLocationCode,
    internalLocationUserDescription = internalLocationUserDescription,
    internalLocationDescription = internalLocationDescription,
    eventId = eventId,
    appointmentSeriesId = appointmentSeriesId,
    appointmentId = appointmentId,
    appointmentAttendeeId = appointmentAttendeeId,
    oicHearingId = null,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = categoryCode,
    categoryDescription = categoryDescription,
    summary = summary,
    comments = comments,
    inCell = false,
    outsidePrison = false,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun activityInstance(
    prisonCode: String = "MDI",
    eventSource: String = "SAA",
    eventType: String = EventType.ACTIVITY.name,
    scheduledInstanceId: Long? = 1L,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    internalLocationId: Long? = 102,
    internalLocationCode: String? = "MDI-EDUC-RM1",
    internalLocationUserDescription: String? = "User description",
    internalLocationDescription: String? = "WORKSHOP 10 - BRICKS",
    eventId: Long? = null,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    categoryCode: String? = "SAA-EDUCATION",
    categoryDescription: String? = "SAA-EDUCATION",
    summary: String? = "Bricks PM",
    comments: String? = null,
    date: LocalDate = LocalDate.of(2022, 12, 16),
    startTime: LocalTime = LocalTime.of(13, 15, 0),
    endTime: LocalTime = LocalTime.of(16, 15, 0),
    priority: Int = 6,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = scheduledInstanceId,
    bookingId = bookingId,
    prisonerNumber = prisonerNumber,
    internalLocationId = internalLocationId,
    internalLocationCode = internalLocationCode,
    internalLocationUserDescription = internalLocationUserDescription,
    internalLocationDescription = internalLocationDescription,
    eventId = eventId,
    appointmentSeriesId = null,
    appointmentId = null,
    appointmentAttendeeId = null,
    oicHearingId = null,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = categoryCode,
    categoryDescription = categoryDescription,
    summary = summary,
    comments = comments,
    inCell = false,
    outsidePrison = false,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun visitInstance(
    prisonCode: String = "MDI",
    eventSource: String = "NOMIS",
    eventType: String = EventType.VISIT.name,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    internalLocationId: Long? = 101,
    internalLocationCode: String? = "SOCIAL VISITS",
    internalLocationUserDescription: String? = "User description",
    internalLocationDescription: String? = "SOCIAL VISITS",
    eventId: Long? = 10002,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    summary: String? = "Visit in family room",
    comments: String? = "Dont be late",
    date: LocalDate = LocalDate.of(2022, 12, 12),
    startTime: LocalTime = LocalTime.of(17, 0, 0),
    endTime: LocalTime = LocalTime.of(18, 0, 0),
    priority: Int = 3,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = null,
    bookingId = bookingId,
    prisonerNumber = prisonerNumber,
    internalLocationId = internalLocationId,
    internalLocationCode = internalLocationCode,
    internalLocationUserDescription = internalLocationUserDescription,
    internalLocationDescription = internalLocationDescription,
    eventId = eventId,
    appointmentSeriesId = null,
    appointmentId = null,
    appointmentAttendeeId = null,
    oicHearingId = null,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = null,
    categoryDescription = null,
    summary = summary,
    comments = comments,
    inCell = false,
    outsidePrison = false,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun courtHearingInstance(
    prisonCode: String = "MDI",
    eventSource: String = "NOMIS",
    eventType: String = EventType.COURT_HEARING.name,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    eventId: Long? = 10002,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    summary: String? = "Court hearing",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime? = null,
    priority: Int = 1,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = null,
    bookingId = bookingId,
    prisonerNumber = prisonerNumber,
    internalLocationId = null,
    internalLocationCode = null,
    internalLocationUserDescription = null,
    internalLocationDescription = null,
    eventId = eventId,
    appointmentSeriesId = null,
    appointmentId = null,
    appointmentAttendeeId = null,
    oicHearingId = null,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = null,
    categoryDescription = null,
    summary = summary,
    comments = null,
    inCell = false,
    outsidePrison = true,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun adjudicationInstance(
    prisonCode: String = "MDI",
    eventSource: String = "NOMIS",
    eventType: String = EventType.ADJUDICATION_HEARING.name,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    internalLocationId: Long? = 101,
    internalLocationCode: String? = "MDI-GOV-OFFICE",
    internalLocationUserDescription: String? = "User description",
    internalLocationDescription: String? = "Governor Office",
    eventId: Long? = 10002,
    oicHearingId: Long? = 1L,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    summary: String? = "Court hearing",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime? = LocalTime.of(14, 0, 0),
    priority: Int = 4,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = null,
    prisonerNumber = prisonerNumber,
    bookingId = bookingId,
    internalLocationId = internalLocationId,
    internalLocationCode = internalLocationCode,
    internalLocationUserDescription = internalLocationUserDescription,
    internalLocationDescription = internalLocationDescription,
    eventId = eventId,
    appointmentSeriesId = null,
    appointmentId = null,
    appointmentAttendeeId = null,
    oicHearingId = oicHearingId,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = null,
    categoryDescription = null,
    summary = summary,
    comments = null,
    inCell = false,
    outsidePrison = true,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun externalTransferInstance(
    prisonCode: String = "MDI",
    eventSource: String = "NOMIS",
    eventType: String = EventType.EXTERNAL_TRANSFER.name,
    prisonerNumber: String = "G1234GG",
    bookingId: Long? = 900001,
    eventId: Long? = 10002,
    cancelled: Boolean = false,
    suspended: Boolean = false,
    summary: String? = "Transfer",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime? = null,
    priority: Int = 2,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventSource = eventSource,
    eventType = eventType,
    scheduledInstanceId = null,
    prisonerNumber = prisonerNumber,
    bookingId = bookingId,
    internalLocationId = null,
    internalLocationCode = null,
    internalLocationUserDescription = null,
    internalLocationDescription = null,
    eventId = eventId,
    appointmentSeriesId = null,
    appointmentId = null,
    appointmentAttendeeId = null,
    oicHearingId = null,
    cancelled = cancelled,
    suspended = suspended,
    categoryCode = null,
    categoryDescription = null,
    summary = summary,
    comments = null,
    inCell = false,
    outsidePrison = true,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )
}
