package uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.service

import uk.gov.justice.digital.hmpps.hmppsactivitiesmanagementapi.model.ScheduledEvent
import java.time.LocalDate
import java.time.LocalTime

object ScheduledEventFixture {
  fun appointmentInstance(
    prisonCode: String = "MDI",
    eventId: Long = 10001,
    bookingId: Long = 900001,
    location: String = "INDUCTION CLASSROOM",
    locationId: Long = 101,
    eventClass: String = "INT_MOV",
    eventStatus: String = "SCH",
    eventType: String = "APPOINTMENT",
    eventTypeDesc: String = "Appointment",
    event: String = "GOVE",
    eventDesc: String = "Governor",
    details: String = "Dont be late",
    prisonerNumber: String = "GF10001",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime = LocalTime.of(13, 0, 0),
    priority: Int = 4,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventId = eventId,
    bookingId = bookingId,
    location = location,
    locationId = locationId,
    eventClass = eventClass,
    eventStatus = eventStatus,
    eventType = eventType,
    eventTypeDesc = eventTypeDesc,
    event = event,
    eventDesc = eventDesc,
    details = details,
    prisonerNumber = prisonerNumber,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun activityInstance(
    prisonCode: String = "MDI",
    eventId: Long = 10001,
    bookingId: Long = 900001,
    location: String = "WORKSHOP 10 - BRICKS",
    locationId: Long = 102,
    eventClass: String = "INT_MOV",
    eventStatus: String = "SCH",
    eventType: String = "PRISON_ACT",
    eventTypeDesc: String = "Prison Activities",
    event: String = "Maths",
    eventDesc: String = "Maths level 1",
    details: String = "Bricks PM",
    prisonerNumber: String = "GF10001",
    date: LocalDate = LocalDate.of(2022, 12, 16),
    startTime: LocalTime = LocalTime.of(13, 15, 0),
    endTime: LocalTime = LocalTime.of(16, 15, 0),
    priority: Int = 5,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventId = eventId,
    bookingId = bookingId,
    location = location,
    locationId = locationId,
    eventClass = eventClass,
    eventStatus = eventStatus,
    eventType = eventType,
    eventTypeDesc = eventTypeDesc,
    event = event,
    eventDesc = eventDesc,
    details = details,
    prisonerNumber = prisonerNumber,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  /*
  fun activityProjectionInstance(
    scheduledInstanceId: Int = 1,
    sessionDate: LocalDate = LocalDate.of(2022, 12, 16),
    startTime: LocalTime = LocalTime.of(13, 15, 0),
    endTime: LocalTime = LocalTime.of(16, 15, 0),
    prisonerNumber: String = "GF10001",
    bookingId: Int = 1,
    internalLocationId: Int = 102,
    internalLocationCode: String = "ROOM1",
    internalLocationDescription: String = "EDU ROOM 1",
    scheduleDescription: String = "HB 1 Mon-Weds",
    activityId: Int = 1,
    activityCategory: String = "Education",
    activitySummary: String = "Maths Level 1",
    activityDescription: String = "A basic maths course",
  ) = ActivityForPrisoner(
    // TODO - make this a data class, instantiable
     scheduledInstanceId = scheduledInstanceId,
     sessionDate = sessionDate,
     startTime = startTime,
     endTime = endTime,
     prisonerNumber = prisonerNumber,
     bookingId = bookingId,
     internalLocationId = internalLocationId,
     internalLocationCode = internalLocationCode,
     internalLocationDescription = internalLocationDescription,
     scheduleDescription = scheduleDescription,
     activityId = activityId,
     activityCategory = activityCategory,
     activitySummary = activitySummary,
     activityDescription = activityDescription,
  )
   */

  fun visitInstance(
    prisonCode: String = "MDI",
    eventId: Long = 10002,
    bookingId: Long = 900001,
    location: String = "SOCIAL VISITS",
    locationId: Long = 101,
    eventClass: String = "INT_MOV",
    eventStatus: String = "SCH",
    eventType: String = "VISIT",
    eventTypeDesc: String = "Visit",
    event: String = "STD VISIT",
    eventDesc: String = "Visit in family room",
    details: String = "Dont be late",
    prisonerNumber: String = "GF10001",
    date: LocalDate = LocalDate.of(2022, 12, 12),
    startTime: LocalTime = LocalTime.of(17, 0, 0),
    endTime: LocalTime = LocalTime.of(18, 0, 0),
    priority: Int = 2,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventId = eventId,
    bookingId = bookingId,
    location = location,
    locationId = locationId,
    eventClass = eventClass,
    eventStatus = eventStatus,
    eventType = eventType,
    eventTypeDesc = eventTypeDesc,
    event = event,
    eventDesc = eventDesc,
    details = details,
    prisonerNumber = prisonerNumber,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )

  fun courtHearingInstance(
    prisonCode: String = "MDI",
    eventId: Long = 10003,
    bookingId: Long = 900001,
    location: String = "Aberdeen Sheriff's Court (abdshf)",
    locationId: Long? = null,
    eventClass: String? = null,
    eventStatus: String? = null,
    eventType: String = "COURT_HEARING",
    eventTypeDesc: String = "Court Hearing",
    event: String = "CRT",
    eventDesc: String = "Leeds court probation hearing",
    details: String = "Dont be late",
    prisonerNumber: String = "GF10001",
    date: LocalDate = LocalDate.of(2022, 10, 1),
    startTime: LocalTime = LocalTime.of(12, 0, 0),
    endTime: LocalTime? = null,
    priority: Int = 1,
  ) = ScheduledEvent(
    prisonCode = prisonCode,
    eventId = eventId,
    bookingId = bookingId,
    location = location,
    locationId = locationId,
    eventClass = eventClass,
    eventStatus = eventStatus,
    eventType = eventType,
    eventTypeDesc = eventTypeDesc,
    event = event,
    eventDesc = eventDesc,
    details = details,
    prisonerNumber = prisonerNumber,
    date = date,
    startTime = startTime,
    endTime = endTime,
    priority = priority,
  )
}
